### ISSUE TITLE
Estimates "stuck" at initial values and ignoring bounds

### ISSUE THREAD

**Issue by llmafrica** [jeffgortmaker/pyblp#111] opened 2022-04-13 21:19 UTC
Hi,

This might be a simple problem, so I apologize if this is basic but I'm new to Python and am encountering a few issues that I'm hoping you might have some insight about. I've attached results files of the two issues, but I'm not sure if there is anything else you might need so please let me know if there is anything else!

First, in two separate models I find that the estimation results seem "stuck" at initial values. If I change the starting values, then the results report the initial values (or very close to them) as the results. The attached examples should show the initial problem set-up. 

Second, I keep finding the results of a different model ignoring any bounds I place on estimates. Example 2 gives the output with the bounds seemingly applied. I edited this file slightly. The following error message originally appeared between each iteration:

"At least one error was encountered. As long as the optimization routine does not get stuck at values of theta that give rise to errors, this is not necessarily a problem. If the errors persist or seem to be impacting the optimization results, consider setting an error punishment or following any of the other suggestions below:
Encountered a numerical error when computing delta. This problem is often due to prior problems, overflow, or nonpositive shares, and can sometimes be mitigated by choosing smaller initial parameter values, setting more conservative bounds on parameters or shares, rescaling data, removing outliers, changing the floating point precision, or using different optimization, iteration, or integration configurations. Errors encountered: divide by zero.
The fixed point computation of delta failed to converge. This problem can sometimes be mitigated by increasing the maximum number of fixed point iterations, increasing the fixed point tolerance, choosing more reasonable initial parameter values, setting more conservative parameter or share bounds, or using different iteration or optimization configurations."

Thank you for any advice!

[stickyvals_example1_pyblp.txt](https://github.com/jeffgortmaker/pyblp/files/8484687/stickyvals_example1_pyblp.txt)
[ignoringbounds_example2_pyblp.txt](https://github.com/jeffgortmaker/pyblp/files/8484690/ignoringbounds_example2_pyblp.txt)

**Comment by jeffgortmaker** [comment] 2022-04-13 22:19
It's a bit hard to tell what the issue is with the optimizer from the log files, but it looks likes something bad is happening. What optimizer are you using? These days I tend to suggest using `optimization=pyblp.Optimization('trust-constr')`, and to tweak its [options](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html) to make things work, e.g. `gtol`.

Another suggestion is to start with a simpler model. For your nested logit case, I'd recommend seeing if you run into a similar problem with only demand-side moments, or with supply-side moments but without the nesting parameter, just to see what's creating issues here. Another way to simplify the model is to temporarily remove the demand-side fixed effects. Let me know what you find.

For the "ignoring the bounds," I think I actually have an immediate answer. When you don't specify initial values for elements of beta (you only specify one for the coefficient on price), the package concentrates them out in a linear IV, and hence ignores any bounds that you may have put on them. If you want to keep beta bounded for some reason, you'll have to specify initial values. (But I don't think I've seen applications where people want to keep linear parameters bounded when they can be concentrated out.)

The fact that you're getting estimated coefficients on the order of 1e14 (and a similarly large condition number for your weighting matrix) suggests that there's a collinearity problem with your X1/instruments. Are you getting any collinearity warnings when you initialize the problem? (You might want to increase the default `pyblp.options.collinear_atol` and `pyblp.options.collinear_rtol` to detect things that are nearly collinear.)

**Comment by jeffgortmaker** [comment] 2022-05-14 12:15
I'm going to close this for now, but feel free to re-open/continue commenting if you're still having issues.

**Closed by jeffgortmaker** 2022-05-14 12:15 UTC
Labels: question
