### ISSUE TITLE
Is minimum distance estimation supported for absorbed product characteristics

### ISSUE THREAD

**Issue by yihao-yuan** [jeffgortmaker/pyblp#85] opened 2021-06-09 20:14 UTC
I would like to estimate coefficients and SEs of product characteristics with product fixed effects, like Nevo (2000, 2001). Does the package support Chamberlain (1982)-style minimum-distance estimation based on estimated fixed effect parameters described by Nevo (2000)? Thank you!

**Comment by jeffgortmaker** [comment] 2021-06-09 22:52
No, but this should be a linear IV-type regression that you can run with the attributes of `ProblemResults`, perhaps with some other package like statsmodels. See also @chrisconlon's related discussion in https://github.com/jeffgortmaker/pyblp/issues/39. Does that help?

**Comment by yihao-yuan** [comment] 2021-06-10 00:07
Thank you, Jeff. I think theoretically instead of absorbing product FEs, I can use product dummies, and then use the coefficients of the dummies for minimum distance regression. The problem is I have too many observations & products in the data, so adding the dummies requires hundreds of GBs and is not feasible. I guess I will leave the product characteristic coefficients for now. Thank you for your quick answer!!

Another question is a warning I ran into:
```
At least one error was encountered. As long as the optimization routine does not get stuck at values of theta that give rise to errors, this is not necessarily a problem. If the errors persist or seem to be impacting the optimization results, consider setting an error punishment or following any of the other suggestions below:
Encountered a numerical error when computing delta. This problem is often due to prior problems, overflow, or nonpositive shares, and can sometimes be mitigated by choosing smaller initial parameter values, setting more conservative bounds on parameters or shares, rescaling data, removing outliers, changing the floating point precision, or using different optimization, iteration, or integration configurations. Errors encountered: divide by zero.
```
So this warning means there are some problems with the convergence of $\delta$ (based on your manual), and the reason is that there are divisions by zero (I don't think ```divide by zero```

**Comment by jeffgortmaker** [comment] 2021-06-10 00:31
Yes -- that sounds right. There may be a way to make this more computationally feasible for some problems, but I haven't thought much about it --- I think the main challenge is getting the covariance matrix, which is quite a large object.

Right, so the "divide by zero" error is tacked on to the default text that you're seeing in the pdf. If you want a more substantive traceback, you can set [`pyblp.options.verbose_tracebacks`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.options.html#pyblp.options.verbose_tracebacks)` = True`. Where the problem occurs will depend on your setup, but in my experience division by zero usually happens when evaluating s_t. You get at least one agent that really likes the outside good so that all her inside good choice probabilities are tiny, and the denominator in the logit choice probability expression underflows to zero.

One way to debug this is to see whether some of your agent draws or demographics are pretty extreme. Agents with really high or really low income are two typical examples that tend to create floating point issues. Of course if the error message goes away after a number of objective iterations, you don't have anything to worry about.

**Comment by yihao-yuan** [comment] 2021-06-10 00:55
Thank you! My confusion is that if one of the agents have a large enough s_it, then s_t should not be zero. I am not using any observable demographics (only random draws from normal distributions), so extreme draw is unlikely to be the reason.

 "the denominator in the logit choice probability expression underflows to zero"—are you saying the numerator instead of the denominator?

**Comment by jeffgortmaker** [comment] 2021-06-10 00:58
Right, so the issue tends to be not that s_t itself is zero, but rather that the denominator of s_it underflows to zero for at least one agent i. But this is just speculation without checking the traceback!

**Comment by yihao-yuan** [comment] 2021-06-10 01:00
Sorry, I may miss something here. Why the denominator of s_it can underflow? Shouldn't it be at least 1 because of the outside option?

**Comment by jeffgortmaker** [comment] 2021-06-10 01:07
You're right -- sorry for the confusion. I was just working on some micro moment expressions where a near-zero inside good creates these issues. But I don't think my guess above applies here. Happy to take a look at the traceback to see where the division by zero is happening.

**Comment by chrisconlon** [comment] 2021-06-10 01:56
Most likely culprit is that you have a very large x_jt for some product
characteristic.
A very large draw v_it for that product characteristic
And a large enough sigma for that characteristic.

Think about what happens if you take exp(900) or something -- all of the
other utilities are effectively zero -- you get that some individual has
s_ij = 1 for some choice with the extreme x_jt and s_ij=0 for everything
else. This is when you will get overflow/underflow messages.

Potential fixes:
1. constrain sigma with bounds
2. try some other set of draws: PMC are not ideal but sometimes high
degrees of quadrature choose points like 8-9 SD away from zero. You can
always switch back to quadrature once you know roughly where the parameters
are.
3. Make sure you don't have some crazy x_jt for some product (the 400k
sports car, etc.)

**Comment by yihao-yuan** [comment] 2021-06-11 03:36
Thank you, Professor Conlon! I am still a little confused by where this "division by zero" warning comes from. Here is the traceback from my program:

 Errors encountered: divide by zero.
The fixed point computation of delta failed to converge. This problem can sometimes be mitigated by increasing the maximum number of fixed point iterations, increasing the fixed point tolerance, choosing more reasonable initial parameter values, setting more conservative parameter or share bounds, or using different iteration or optimization configurations. Traceback:

  File "3_blp_elasticity.py", line 266, in <module>
    results = problem.solve(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 638, in solve
    theta, optimization_stats = optimization._optimize(theta, theta_bounds, wrapper)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 289, in _optimize
    raw_final, converged = self._optimizer(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 329, in scipy_optimizer
    results = scipy.optimize.minimize(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 608, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 744, in _minimize_neldermead
    fxe = func(xe)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 461, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 314, in objective_wrapper
    cache = (values.copy(), objective_function(values))
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 278, in objective_wrapper
    objective, gradient = verbose_objective_function(values, iterations, evaluations)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 619, in wrapper
    progress = compute_step_progress(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 717, in _compute_progress
    self._compute_demand_contributions(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 907, in _compute_demand_contributions
    for t, generated_t in generator:
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 94, in <genexpr>
    return (generate_items_worker((k, factory(k), method)) for k in keys)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 103, in generate_items_worker
    return key, method(instance, *method_args)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/markets/problem_market.py", line 30, in solve_demand
    delta, clipped_shares, stats, delta_errors = self.safely_compute_delta(delta, iteration, fp_type, shares_bounds)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 557, in wrapper
    returned = decorated(*args, **kwargs)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/markets/problem_market.py", line 112, in safely_compute_delta
    errors.append(exceptions.DeltaConvergenceError())
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 416, in __init__
    self.stack = ''.join(traceback.format_stack())

I think the problem should be with the log(s_j) step instead of exp(u_ij) because the "divide by zero" warning shows up when s_j is smaller than 1e-323. I am a little surprised that it would happen because that needs all s_ij to be really small. I will take suggestions and try to drop some price outliers first. Thank you very much for your kind help!

**Comment by jeffgortmaker** [comment] 2021-06-11 17:10
Is that the only traceback that shows up? The traceback you posted is the one for the "The fixed point computation of delta failed to converge" error. Ideally we'd want to see the one for the "Encountered a numerical error when computing delta" error -- that should be more informative about where the numerical error is occurring.

Another thing I'll mention is that by default, the `shares_bounds=(1e-300, None)` argument to [Problem.solve](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Problem.solve.html) clips small shares from below by `1e-300` before taking a log (and it records any clipped share counts in printed status updates). So I'm not sure if this is where the problem is.

**Comment by yihao-yuan** [comment] 2021-06-11 17:55
Hi Jeff, Thank you for your response and or pointing out that you set share minimum to 1e-300. There is another traceback as below. 

At least one error was encountered. As long as the optimization routine does not get stuck at values of theta that give rise to errors, this is not necessarily a problem. If the errors persist or seem to be impacting the optimization results, consider setting an error punishment or following any of the other suggestions below:
Encountered a numerical error when computing delta. This problem is often due to prior problems, overflow, or nonpositive shares, and can sometimes be mitigated by choosing smaller initial parameter values, setting more conservative bounds on parameters or shares, rescaling data, removing outliers, changing the floating point precision, or using different optimization, iteration, or integration configurations. Traceback:

  File "3d_blp_elasticity.py", line 270, in <module>
    results = problem.solve(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 638, in solve
    theta, optimization_stats = optimization._optimize(theta, theta_bounds, wrapper)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 289, in _optimize
    raw_final, converged = self._optimizer(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 329, in scipy_optimizer
    results = scipy.optimize.minimize(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 608, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 744, in _minimize_neldermead
    fxe = func(xe)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 461, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 314, in objective_wrapper
    cache = (values.copy(), objective_function(values))
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/optimization.py", line 278, in objective_wrapper
    objective, gradient = verbose_objective_function(values, iterations, evaluations)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 619, in wrapper
    progress = compute_step_progress(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 717, in _compute_progress
    self._compute_demand_contributions(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/economies/problem.py", line 907, in _compute_demand_contributions
    for t, generated_t in generator:
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 94, in <genexpr>
    return (generate_items_worker((k, factory(k), method)) for k in keys)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 103, in generate_items_worker
    return key, method(instance, *method_args)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/markets/problem_market.py", line 30, in solve_demand
    delta, clipped_shares, stats, delta_errors = self.safely_compute_delta(delta, iteration, fp_type, shares_bounds)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 557, in wrapper
    returned = decorated(*args, **kwargs)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/markets/problem_market.py", line 110, in safely_compute_delta
    delta, clipped_shares, stats, errors = self.compute_delta(initial_delta, iteration, fp_type, shares_bounds)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/markets/market.py", line 477, in compute_delta
    delta, stats = iteration._iterate(initial_delta, contraction)
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/iteration.py", line 279, in _iterate
    raw_final, converged = self._iterator(
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/configurations/iteration.py", line 425, in squarem_iterator
    alpha = -np.sqrt((r.T @ r) / (v.T @ v))
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 579, in __call__
    self.detected = self.error()
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 483, in __init__
    super().__init__()
  File "/home/mktg/yihaoy/venv38/lib/python3.8/site-packages/pyblp/utilities/basics.py", line 416, in __init__
    self.stack = ''.join(traceback.format_stack())

**Comment by jeffgortmaker** [comment] 2021-06-11 18:14
Ah interesting. The issue is actually coming from the SQUAREM acceleration routine we're using to speed up the fixed point.

It seems like when two fixed point iterations are sufficiently close to one another, the denominator in the step length `alpha` can underflow. But the algorithm clips `alpha` to within some bounds afterwards, so I think it's safe to ignore this error (instead of terminating the algorithm) as I've now done in 6649932a7191bad656727b5d27281a6622d3ad77.

If you clone the dev version of the code from this repo, I'm hoping that you won't see this error any more. That said, unusual SQUAREM behavior doesn't bode well for the stability of the rest of your problem, but maybe you'll now have one fewer error. If SQUAREM still isn't working well, I'd also try a different [`Iteration`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.Iteration.html) `method`, for example `'lm'` or even just `'simple'`.

**Comment by yihao-yuan** [comment] 2021-06-15 20:03
Hi Jeff, thank you for your comment. I tried to (i) ignoring the error, and (ii) use ```'simple'``` instead. The two methods still give quite different results. I guess this is because of the ```The fixed point computation of delta failed to converge``` problem. It only happens under (i) but not under (ii). I am not sure what is going on here. However, ```simple``` works pretty good and gives credible results, though it's really slow. I think I will stick with ```simple``` for now.

Thank you for your quick responses, and great work and updates on pyBLP. It really helps a lot of people like me!

**Comment by jeffgortmaker** [comment] 2021-06-15 20:57
Great! The `'lm'` procedure may speed things up if estimation speed turns into a bottleneck for you (or the patched `'squarem'` in the next package release, whenever that will be), although there's nothing wrong with doing `'simple'` iteration if it gives no errors.

Glad you're finding the package helpful! I'll close this issue for now, but feel free to re-open or open another if you're having more issues.

**Closed by jeffgortmaker** 2021-06-15 20:57 UTC
Labels: bug, question
