### ISSUE TITLE
Question: How to create a 'two-step market share'

### ISSUE THREAD

**Issue by turntabler** [jeffgortmaker/pyblp#57] opened 2020-05-13 03:59 UTC
Hello Jeff,
I first wanted to thank you and Chris for putting together the package, it has been very helpful.
I had a question on implementing the current setting: imagine a nested logit model with a distance function where, first, consumers decide which firm in the market to go to, and then they decide among the firms' products. This is similar to Holmes (2011).
Then, the choice probability looks something like this:
$s_{jfz}=s_{jfz|f}*s_{fz}$, where j is a product, f is a firm, and z is the consumer's location.
$s_{jfz|f}$ is the usual nested logit expression, exp(\delta_{jf}/(1-\sigma))/(1+\sum_{j'}exp(...)), where $\delta_{jf}=\alpha p_{jf}+\beta X_{jf}+\xi_{jf}$ and $s_{fz}=exp(g(d_{fz},\lambda)/(1+\sum_{f'}exp(...))$
It seems like I can only define the first part in the nested logit pyblp tutorial. And if I include the distance function as another set of variables in the problem formulation, then I pick up $\xi$'s that are at the jfz level rather than at the jf level. In my mind, the solution would involve having one formulation denoting what goes into the delta, and a second formulation denoting what goes into the distance function. However, putting it together in the pyblp setting is proving tricky.
Any suggestions? Maybe there is an easier way. Picking up \xi at the 'correct' level (firm-product, not firm-product-consumer) is what I need
Thank you

**Comment by turntabler** [comment] 2020-05-13 04:17
just to be clear, the nests are with respect to the firm f. so as sigma goes to 1, all consumers stay within a firm and substitute along this firm's products.

**Comment by jeffgortmaker** [comment] 2020-05-13 14:43
It would help if you wrote down the utility specification that gives rise to these choice probabilities.

If this isn't a special case of the (RC)NL model, then I'm afraid PyBLP is unlikely to support it. Of course contributions are welcome, although I'd be hesitant to support a model that's only used by one or two papers.

**Comment by turntabler** [comment] 2020-05-13 15:04
Yes, I should have done that sooner.
the utility function looks like:
u_{jfz}=\alpha p_{jf}+\beta X_{jf} +\xi_{jf} +g(d_{fz},\lambda)+\zeta_{fz}+(1-\sigma)\epsilon_{jfz}
It does look like the RCNL model, the only difference is that g(d_{fz},\lambda)=\lambda_{1}d_{fz} is completely parametric (and nonrandom).

**Comment by jeffgortmaker** [comment] 2020-05-13 15:27
Thanks, that's helpful. In that expression, if you replace `z` with `i`, replace `f` with `h(j)`, rename `\sigma` to `rho`, rename `\zeta` to `\epsilon`, and swap around the order of some things, then you get

```
u_{ij} = \alpha p_j + \beta X_j + \lambda d_{ih(j)} + \xi_j + \epsilon_{ih(j)} + (1 - \rho) \epsilon_{ij}.
```

Note that I've suppressed the nesting indices in some places. Does this look the same to you?

If so, I think this might be a special case of the [(RC)NL model](https://pyblp.readthedocs.io/en/stable/background.html#random-coefficients-nested-logit), which differs from the homogeneous NL model because of the term `\lambda d_{ih(j)}` that incorporates demographics. I think you should be able include this term via agent data and a properly-designed [`\Pi` matrix](https://pyblp.readthedocs.io/en/stable/background.html#equation-mu). Thoughts?

**Comment by chrisconlon** [comment] 2020-05-13 15:43
It seems like what you've described is the RCNL model.

First consumers choose a nest (firm). Then they choose a product.

The only wrinkle you've added is that you have consumers living in different distance bins (z) to each store. These are in practice easy to model as demographic draws.

Here are two ways you could do this:
1. For each location "z", you calculate the distance to each possible store "f" and you can model these as demographic interactions. The downside is that you need one for each store -- so this is potentially a lot of parameters. The other downside is that this would assume that you only have aggregate data at the "store" level not the "store x geography" level. The hard part is that you probably want the coefficient on each of these "Pi" (demographic) distance variables to be identical.

2. If you had data at the "store x geography" level then distance to each store is an observable "x" characteristic and you are just describing a conventional nested logit where each "market" is a "location". The hard part is that now you would probably want the unobservable qualities to be identical across markets (\xi_{jfz} = \xi_{jf} in your notation).

**Comment by turntabler** [comment] 2020-05-13 16:41
Thank you, this is helpful. 
I will try (1).
With regard to (2), if I have "store x geography", any suggestions on how to make it identical? Or a way to 'extract' the \xi_{jf} from the \xi_{jfz}? One cheap way I am thinking is, post-estimation, compute \xi_{jf} as an average across z's, so we get \xi_{jfz}=\bar{\xi{jf}} +\Delta \xi_{jfz}. I don't know how appropriate this is, though.

**Comment by chrisconlon** [comment] 2020-05-14 14:47
Actually -- I think an easier way to think about the question is this:

Is there a one-to-one mapping between xi and share?

If the answer is no, then this isn't really a "BLP" problem and it will be hard to shoehorn into our framework. For example if we observe store x geography shares we are supposed to match but that the unobservable is at the store level. Then the issue is that we have more shares to match than xi's and we can't find an inverse. 

If you're ok with projecting xi_{jfz} onto stuff (like store dummies) and you are interested in only the residual of that -- then you are ok. I will caution that firms probably aren't able to set prices with the geography x store specific deviation in mind.

This seems like something people have tried in the past -- so if you can send a reference that might be helpful to see what they did.

**Comment by jeffgortmaker** [comment] 2020-05-24 18:41
I'm going to close this for now. But feel free to re-open/keep commenting if you have other questions about this.

**Closed by jeffgortmaker** 2020-05-24 18:41 UTC
Labels: question

**Comment by jeffgortmaker** [comment] 2021-11-03 23:36
Following up on this, fb72dcf9e61c154d7a149e84eb4c507489e5c64e adds support for product-specific demographics to the dev version of the code (still needs some testing, but it should work as-is), which should help with having an identical `Pi` parameter for your distance variable. The end of the [dev documentation](https://pyblp.readthedocs.io/en/latest/_api/pyblp.Problem.html) for `agent_data` has more details on how to specify product-specific demographics.
