### ISSUE TITLE
Simulating change in product characteristics with fixed effects

### ISSUE THREAD

**Issue by bardwnb** [jeffgortmaker/pyblp#66] opened 2020-09-15 13:06 UTC
I'm trying to estimate a counterfactual which involves a change in product characteristics.  My problem is set up with firm fixed effects being absorbed.  It would seem that the canonical way to do this inside the pyblp package would be to initialize a Simulation method using the formulations, agent data, beta, sigma, pi and xi from my solved problem, then use Simulation.replace_endogenous to calculate counterfactual prices and shares.  The problem with this seems to be that, on the one hand, the Simulation method won't allow for absorbing fixed effects in the X1 formulation, and on the other hand the required beta argument from my solved is shorter than the X1 formulation (in my particular case I have 11 beta coefficients, but with firm effects the Simulation expects 34).

Is there any way around this? If not, is there any appropriate way to use the pyblp utilities to simplify coding this up outside the package?

**Comment by jeffgortmaker** [comment] 2020-09-15 13:53
You have two options that I can think of:

1. Don't absorb firm FEs when estimating your model.
2. Instead of passing `xi` to `Simulation`, pass `xi + delta - X1 @ beta`. When FEs are absorbed, [`ProblemResults.xi`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.ProblemResults.html#pyblp.ProblemResults.xi) is actually \Delta\xi [here](https://pyblp.readthedocs.io/en/stable/background.html#fixed-effects), and the second term is the FEs' contribution to unobserved quality.

Will one of those work for you?

**Comment by bardwnb** [comment] 2020-09-15 14:43
Thanks for the quick response.  2 should work, though since I'm accessing pyblp from R via reticulate, I may have to get creative, since the contents of results.problem.products seem to be stored in a format that can't translate back to R.  But it's easy enough to reconstruct the X1 matrix from R.

**Comment by jeffgortmaker** [comment] 2020-09-15 15:01
Ah, I didn't realize that reticulate doesn't play nice with numpy structured arrays. That's too bad. The simplest thing might be to use [`build_matrix`](https://pyblp.readthedocs.io/en/stable/_api/pyblp.build_matrix.html#pyblp.build_matrix) with your same X1 formula that you used to initialize your problem.

I'll close the issue now but feel free to re-open if something doesn't work.

**Closed by jeffgortmaker** 2020-09-15 15:01 UTC
Labels: question

**Comment by AdrianMorenoMaria** [comment] 2024-08-09 08:43
Hi, I have the same problem. I followed the second option you stated, just to pass results.delta - results.problem.products.X1 @ results.beta. However, in the simulation I miss the intercept as in the first case I used "absorb" and the beta is not the same size. Any suggestion?

**Comment by jeffgortmaker** [comment] 2024-08-09 14:28
This issue was from a while ago -- there's now a `ProblemResults.xi_fe` that you can add to `ProblemResults.xi`. See, e.g., the discussion in https://github.com/jeffgortmaker/pyblp/issues/161. Does that help?

**Comment by AdrianMorenoMaria** [comment] 2024-08-09 14:49
Yes it helps but I still have an issue. Since in my formulation I incorporate dummy variables (product characteristics) in the simulation process since we do not incorporate in the formulation the "absorb" FE, I still have one more beta than in the initial problem. I do not really know if there is any way to manage that. I would appreciate any help.

Many thanks

**Comment by jeffgortmaker** [comment] 2024-08-09 15:06
Why is it that you're including dummy variables in your simulation but not your estimation? The `xi + xi_fe` will already account for them. Are you trying to change one of the dummies for a counterfactual?

**Comment by AdrianMorenoMaria** [comment] 2024-08-12 08:15
No, but if in the initial estimation we include "absorb", since it is demeaned the intercept is removed. However, since the simulation does not accept the option "absorb" the intercept is maintained and then we have one more beta than before.

**Comment by jeffgortmaker** [comment] 2024-08-12 13:50
I see. Sounds like you should just start your `Simulation` formulation with a `0 +` to eliminate its constant, and use `xi + xi_fe`. Does that work?

**Comment by AdrianMorenoMaria** [comment] 2024-08-22 10:36
Sure, here is the initial formulation:

X1_formulation = pyblp.Formulation('1 + prices + C(Watts) + C(TYPEGC_gr) + C(channel_id)', absorb='C(brand_ids)  + C(country) + C(year)')

X2_formulation = pyblp.Formulation('1 + prices')

product_formulations = (X1_formulation, X2_formulation)


where watts is a dumy variable for wattage of the product, and TYPEGC_gr a categorical variable for different types of the product. Channel takes values 0, 1 or 2, deppending on the sales channel.

In the simulation what I do is to remove channel_id==2.

The problem in the simulation is that since absorb cannot be used, it does not demean as in the initial case. And if I set a formulation with a 0 +, it still adds an extra component for the baseline of the first dummy.

**Comment by jeffgortmaker** [comment] 2024-08-22 11:50
Ah, I think I understand now. The issue seems to be with the inflexibility of the convenience function `C`. A solution is just to not rely on `C` to create dummy variables, and instead construct them manually. For example, something like

```python
formula = '0 + prices'
for key in ['Watts', 'TYPEGC_gr', 'channel_id']:
    for level in product_data[key].unique()[1:]:
        product_data[f'{key}_{level}'] = (product_data[key] == level).astype(float)
        formula = f'{formula} + {key}_{level}'
````

Note that `1:` drops the first level for each set of non-absorbed fixed effects.

You would use this same formula for both estimation (where you also include the `absorb` as above, still using `C`) and simulation (where you pass the estimated `xi + xi_fe`).

Will something like that work? (You could probably do something cleaner with [`pd.get_dummies`](https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html).)

**Comment by AdrianMorenoMaria** [comment] 2024-08-25 09:26
I understand you but the issue still appears. I followed your recommendation but for the first variable Watts, it still uses the 0 value of the dummy as "intercept" giving an extra beta compared to the formulation with absorb

**Comment by jeffgortmaker** [comment] 2024-08-25 14:33
Can you provide a [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example)? Your code for your estimation and simulation X1 formulations, and the resulting problem/simulation output? Otherwise it's nearly impossible for me to help without just taking shots in the dark.

**Comment by AdrianMorenoMaria** [comment] 2024-08-25 15:06
Sure! I already introduce it using the approximation you told me with the dummy:

X1_formulation = pyblp.Formulation('0 + prices + Watts_1 + Watts_2 + EPAFILTER_gr_1 + specialanimal_g_1 + controlshand_g_1 + TYPEGC_gr_1 + TYPEGC_gr_2 + TYPEGC_gr_3 + channel_id_1 + channel_id_2')

<img width="628" alt="Captura1" src="https://github.com/user-attachments/assets/28826594-4ddd-44b8-aae0-60bb5b3bff0f">

and the simulation after removing channel_id_2, what I first did was to remove the beta from the previous result associated to channel_2: **updated_beta** = beta[:-1] and to update all elements as xi, costs, etc to remove the observations associated to channel_2.

After that I set the simulation:
X1_formulation2 = pyblp.Formulation('0+ prices + Watts_1 + Watts_2 + EPAFILTER_gr_1 + specialanimal_g_1 + controlshand_g_1 + TYPEGC_gr_1 + TYPEGC_gr_2 + TYPEGC_gr_3 + channel_id_1')

Then running the simulation I get: 

**ValueError: beta must be 11 by 1.**

Why this? because If I run the initial formulation without the "absorb" as:
X1_formulation = pyblp.Formulation('0 + prices + Watts_1 + Watts_2 + EPAFILTER_gr_1 + specialanimal_g_1 + controlshand_g_1 + TYPEGC_gr_1 + TYPEGC_gr_2 + TYPEGC_gr_3 + channel_id_1 + channel_id_2')

What I get is:
<img width="676" alt="Captura2" src="https://github.com/user-attachments/assets/6abde5fa-48e8-440b-9798-33ea5eb858da">

It takes the "false" value or the 0 of watts as reference. So that's why even doing this I need an extra beta

**Comment by jeffgortmaker** [comment] 2024-08-25 15:10
Oh, did you not use the `.astype(float)` above? I think your indicators are booleans, and [patsy](https://patsy.readthedocs.io/en/latest/) treats these as categorical variables with potentially multiple levels. So it's still implicitly using the `C` function. If you have your manually-constructed indicators be floats instead of booleans, I don't think it should add an extra `[False]`.

**Comment by AdrianMorenoMaria** [comment] 2024-08-26 08:02
Thank you very much Jeff, that works!
